[package]
name = "bevy_jam_4"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
